# Generated by Django 5.0.6 on 2024-06-28 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_receiver_alter_message_sender_and_more'),
        ('events', '0003_eventroom'),
        ('tours', '0002_tour_interested_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventroom',
            name='event',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_chat_room', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventroom',
            name='participants',
            field=models.ManyToManyField(related_name='event_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourroom',
            name='participants',
            field=models.ManyToManyField(related_name='tour_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourroom',
            name='tour',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tour_chat_room', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='eventroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_eventrooms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_tourrooms_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
