# Generated by Django 5.0.6 on 2024-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_eventroom_event_eventroom_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventroom',
            name='photo',
            field=models.ImageField(blank=True, default='event-room/default.jpg', null=True, upload_to='event-room/'),
        ),
        migrations.AddField(
            model_name='tourroom',
            name='photo',
            field=models.ImageField(blank=True, default='tour-room/default.jpg', null=True, upload_to='tour-room/'),
        ),
    ]
