# Generated by Django 5.0.6 on 2024-06-28 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyrating',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.touristcompletedtour'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='eventmanagerrating',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcompleted'),
        ),
        migrations.AddField(
            model_name='eventmanagerrating',
            name='eventmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.eventmanager'),
        ),
        migrations.AddField(
            model_name='guide',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='guiderating',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.guide'),
        ),
        migrations.AddField(
            model_name='guiderating',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.touristcompletedtour'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to='accounts.customuserprofile'),
        ),
        migrations.AddField(
            model_name='guiderating',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist'),
        ),
        migrations.AddField(
            model_name='eventmanagerrating',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist'),
        ),
        migrations.AddField(
            model_name='agencyrating',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist'),
        ),
    ]
