# Generated by Django 5.0.6 on 2024-06-28 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
