# Generated by Django 5.0.6 on 2024-06-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRoom',
        ),
    ]
